# Branch definition: only build master and PRs
branches:
  only:
    master

# Build definition; language, deps, scripts
language: python
python:
  - "3.6"
install:
  - pip install -r requirements/dev.txt
  - pip install codecov
script:
  - coverage run manage.py test
after_success:
  - codecov
